### ISSUE TITLE
Physical Security Solutions - content & layout

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#21]
Layout = 
Content Link = https://docs.google.com/document/d/15zgLReN74R6q8nzvThUHB4E8DhJU3RW0QAWZmpgldeQ/edit?ts=56828ce5

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Layout=http://theme.stepofweb.com/Smarty/v1.1.2/HTML/portfolio-single-parallax.html

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Layout = http://theme.stepofweb.com/Smarty/v1.1.2/HTML/portfolio-single-parallax.html
Content Link =
https://drive.google.com/open?id=0B95j4zfm5LiLU0ZXRkhod2FFd0k
https://drive.google.com/open?id=0B95j4zfm5LiLNTZaNEJkVTJOSGM
https://drive.google.com/open?id=0B95j4zfm5LiLRm5QOXlhdXlnUUU

**Comment by SpecialKelsey** [comment]
Layout = http://theme.stepofweb.com/Smarty/v1.1.2/HTML/page-services-1.html
Content = https://drive.google.com/open?id=0B95j4zfm5LiLU0ZXRkhod2FFd0k
https://drive.google.com/open?id=12XK1go8v4jp171qSi6d5n034zIQcZ62h0bvVyLlOwxU
Pictures Only = https://drive.google.com/open?id=0B95j4zfm5LiLRm5QOXlhdXlnUUU

I'll do a mock up.  I think this one works the best.  We may need a little bit of tweaking but it should work. Where the icons are, we can add a bit more to touch on all of the aspects of Altel security.

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Content =https://drive.google.com/open?id=0B95j4zfm5LiLS0hfcjJlSzkzOGs
Pictures only =https://drive.google.com/open?id=0B95j4zfm5LiLWURFTUdUM3owTUU
Mock up = https://drive.google.com/open?id=0B95j4zfm5LiLNVVIQkVTSmgyLVk

I changed the content a little - added why choose us.  From the mock up I think you will be able to see where the text goes. If not, let me know and I'll break it down.

**Comment by sinkinsona** [comment]
@SpecialKelsey have a look at provide me your feedback 
http://sabytel.com/demo/physical-security-solutions.php

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Hi Andrew,
The  Text for the second Icon has the title Integration of ERP system. That line of text is part of the Access Control text.    It should be Camera Surveillance.  
When you open the tab, there is a typo in the text- it says Physical Securoty instead of Security
![ph](https://cloud.githubusercontent.com/assets/16320855/15398565/16bfa52c-1db2-11e6-8ff6-77c0b8d12f33.jpg)
The drop down menu has Physical TRA and Physical TRA Solution - Not required since there is only one page

**Comment by sinkinsona** [comment]
made the requested fixes
