### ISSUE TITLE
Add initial content

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#6]
Add the following pages to the site

-About Us
https://drive.google.com/file/d/0B95j4zfm5LiLS3RlSGZXMklYTmM/view?usp=sharing_eid&ts=568be5c1

-You Need Us https://docs.google.com/document/d/1pf9fmciDdHd71n4pX4QUZQ0mrN03kexUOQVmxDPaAn4/edit?usp=sharing_eid&ts=56828ce5

-What we can do for you
https://docs.google.com/document/d/15U4VKvn5jACaDuLRPc9Ima93Nci8a3Yr9TeQDTOTxpg/edit?usp=sharing_eid&ts=56828ce5

-Careers
https://drive.google.com/file/d/0B95j4zfm5LiLS1JJa3dTUXh0cmM/view?usp=sharing_eid&ts=56828ce5

-Contact Us
https://drive.google.com/file/d/0B95j4zfm5LiLSGx2N05QdUlZcnc/view?usp=sharing_eid&ts=56828ce5

-Cyber and ICT Security Services What We Do
https://docs.google.com/document/d/1gUREYnUnn1RNGApFRulRHSY04ntc0tBS_ZGoNFPqGno/edit?ts=56828ce5

-Security Systems tailored to your needs
https://docs.google.com/document/d/15zgLReN74R6q8nzvThUHB4E8DhJU3RW0QAWZmpgldeQ/edit?ts=56828ce5

**Comment by sinkinsona** [comment]
@SpecialKelsey can you confirm the page layout and under which menu you would like to have this content under?  For the contact Us and Careers content no need to specify as you provided this info already.  Thx

**Comment by SpecialKelsey** [comment]
@sinkinsona, @Sabytel @ahmedhussein 
Hi Andrew,  Sorry for the late reply.  I have one more page I need to add 
https://drive.google.com/open?id=0B95j4zfm5LiLS3RlSGZXMklYTmM
This one is   About Us.  
As for the rest of the layout I think this would work best. I'm not sure which layouts were chosen for the Services pages so I'll go with I know for now.

Tope Menu:  Home, About Us, Services, Contact Us, Careers, News

Home:  I'm working on the text to add where it says Smarty:  Four areas of expertise.  We need to have images to go with the text.

About Us:  
What We Can Do For You 
You Need us

Services: 
Cyber and ICT Security - What we do 
Physical Security: Security Systems tailored to your needs

If the Smarty layout 2 is chosen for the Services page, here are my suggestions. 
When you click on the icon, it would be direct you to the text of each solution These are all part of the Cyber and ICT Security Services What We Do document

The top part where the icons are would be broken down into: 
Security Research & Development
Data Security
Individual Security Documentation
Cloud computing 
Business Continuity/ Disaster Recovery Plan
Risk Management
Identity Management Solution (IMS)
Vulnerability Assessment (VA)/ Penetration Testing 
Incident Handling
Certification to Information Security Management Systems (ISMS)

The titles may change a little bit because some are quite long.  My view would be for the icons and the text under the icon:
Security for the Icon and the text: Encryption, intrusion detection and anti-malware
Data Security for the Icon and the text:  Protection, guidance and tools
Security Documentation for the Icon and the text: IT Security plan, process and solutions
Cloud computing for the Icon and the text:  Efficient and secure solutions
Disaster Recovery for the Icon and the text: Business continuity protection
Risk Management for the Icon and the text:  Effectively mitigate security risks
Identity Management for the Icon and the text: Identify, implement and manage solutions
Vulnerability for the Icon and the text:  Prevent weaknesses and exposures
Incident Handling for the Icon and the text:  Limit crisis, emergencies or disaster
Certification for the Icon and the text: Information Security Management Systems and ISO training.

For the bottom part of the page for Services, the Smarty apps shows a telephone with icons and little blurb of text.  So same concept as the top part but change the phone picture to something that relates to Physical Security and remove the text and just have text for the Icon.  The text for the icon is found on the document Security Systems tailored to your needs 

Access Control
Identification Systems
Intrusion detection
Electronic modules
Computer infrastructure
Identification card production
Customer Service


I also need to work on the text for Why Choose Us that is displayed at the bottom of the page.

Thoughts, comments, suggestion are always welcome.

**Comment by sinkinsona** [comment]
Adding the link to the About Us page

-About Us
https://drive.google.com/file/d/0B95j4zfm5LiLS3RlSGZXMklYTmM/view?usp=sharing_eid&ts=568be5c1

**Comment by SpecialKelsey** [comment]
@sinkinsona . @ahmedhussein , @Sabytel 

Here is a very quick mark up of what I think the Services page should look like.  

[New Sabytel-Services Web Page.docx](https://github.com/Sabytel-Web/sabytel/files/78661/New.Sabytel-Services.Web.Page.docx)

**Comment by sinkinsona** [comment]
Created new separate issues
